package POJOs_basket_destino_hibernate;
// Generated 14-feb-2022 9:56:50 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Partidos generated by hbm2java
 */
@Entity
@Table(name="partidos"
    ,catalog="basket_destino"
)
public class Partidos  implements java.io.Serializable {


     private PartidosId id;
     private Equipos equiposByElocal;
     private Equipos equiposByEvisitante;
     private String resultado;
     private Integer resultadolocal;
     private Integer resultadovisitante;
     private Integer arbitro;

    public Partidos() {
    }

	
    public Partidos(PartidosId id, Equipos equiposByElocal, Equipos equiposByEvisitante) {
        this.id = id;
        this.equiposByElocal = equiposByElocal;
        this.equiposByEvisitante = equiposByEvisitante;
    }
    public Partidos(PartidosId id, Equipos equiposByElocal, Equipos equiposByEvisitante, String resultado, Integer resultadolocal, Integer resultadovisitante, Integer arbitro) {
       this.id = id;
       this.equiposByElocal = equiposByElocal;
       this.equiposByEvisitante = equiposByEvisitante;
       this.resultado = resultado;
       this.resultadolocal = resultadolocal;
       this.resultadovisitante = resultadovisitante;
       this.arbitro = arbitro;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="elocal", column=@Column(name="elocal", nullable=false) ), 
        @AttributeOverride(name="evisitante", column=@Column(name="evisitante", nullable=false) ), 
        @AttributeOverride(name="fecha", column=@Column(name="fecha", nullable=false, length=10) ) } )
    public PartidosId getId() {
        return this.id;
    }
    
    public void setId(PartidosId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="elocal", nullable=false, insertable=false, updatable=false)
    public Equipos getEquiposByElocal() {
        return this.equiposByElocal;
    }
    
    public void setEquiposByElocal(Equipos equiposByElocal) {
        this.equiposByElocal = equiposByElocal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="evisitante", nullable=false, insertable=false, updatable=false)
    public Equipos getEquiposByEvisitante() {
        return this.equiposByEvisitante;
    }
    
    public void setEquiposByEvisitante(Equipos equiposByEvisitante) {
        this.equiposByEvisitante = equiposByEvisitante;
    }

    
    @Column(name="resultado", length=7)
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }

    
    @Column(name="resultadolocal")
    public Integer getResultadolocal() {
        return this.resultadolocal;
    }
    
    public void setResultadolocal(Integer resultadolocal) {
        this.resultadolocal = resultadolocal;
    }

    
    @Column(name="resultadovisitante")
    public Integer getResultadovisitante() {
        return this.resultadovisitante;
    }
    
    public void setResultadovisitante(Integer resultadovisitante) {
        this.resultadovisitante = resultadovisitante;
    }

    
    @Column(name="arbitro")
    public Integer getArbitro() {
        return this.arbitro;
    }
    
    public void setArbitro(Integer arbitro) {
        this.arbitro = arbitro;
    }




}


