/*
 * Cliente.java
 *
 * Generated with Matisse Schema Definition Language 9.1.12
 * Generation date: Mon Feb 17 13:50:01 2020
 */
// Note: the package and extends declarations are generated by mt_sdl, do not modify them
package inmobiliaria;

import com.matisse.reflect.*;

/**
 * <code>Cliente</code> is a schema class generated by <code>mt_sdl</code>. Any
 * user-written classes will be found at the end of the file, after the '// END
 * of Matisse SDL Generated Code' comment. Attribute types, default values, and
 * relationship minimum and maximum cardinality are stored in the database
 * itself, not in this source code. For more information, see <i>Getting Started
 * with MATISSE</i>.
 */
public class Cliente extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.12
     * Generation Date: Mon Feb 17 13:50:01 2020
     */

 /*
     * Class variables and methods
     */
    /**
     * Class <code>Cliente</code> cache ID
     */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("inmobiliaria.Cliente"));

    /**
     * Gets the <code>Cliente</code> class descriptor. This method supports
     * advanced MATISSE programming techniques such as dynamically modifying the
     * schema.
     *
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass) db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by
     * <code>MtObjectFactory</code>. It is public for technical reasons but is
     * not intended to be called directly by user methods.
     *
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Cliente(com.matisse.MtDatabase db, int mtOid) {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the
     * database. It is protected for technical reasons but is not intended to be
     * called directly by user methods.
     *
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Cliente(com.matisse.reflect.MtClass mtCls) {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     *
     * @param <E> a MtObject class * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Cliente.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     *
     * @param <E> a MtObject class * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server
     * at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Cliente.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     *
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding
     * subclasses).
     *
     * @param <E> a MtObject class * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Cliente.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding
     * subclasses).
     *
     * @param <E> a MtObject class * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server
     * at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Cliente.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     *
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

 /* Attribute 'dni' */
    /**
     * Attribute <code>dni</code> cache ID
     */
    private static int dniCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("dni", CID));

    /**
     * Gets the <code>dni</code> attribute descriptor. This method supports
     * advanced MATISSE programming techniques such as dynamically modifying the
     * schema.
     *
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getDniAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute) db.getCachedObject(dniCID);
    }

    /**
     * Gets the <code>dni</code> attribute value.
     *
     * @return the value
     *
     * @see #setDni
     * @see #removeDni
     */
    public final String getDni() {
        return getString(getDniAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>dni</code> attribute value.
     *
     * @param val the new value
     *
     * @see #getDni
     * @see #removeDni
     */
    public final void setDni(String val) {
        setString(getDniAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>dni</code> attribute value. Falls back to the
     * default value is there is one. If the attribute has no default value, it
     * must be set to a new value before commit.
     *
     * @see #getDni
     * @see #setDni
     */
    public final void removeDni() {
        removeValue(getDniAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     *
     * @return true if null value
     *
     * @see #getDni
     * @see #setDni
     */
    public final boolean isDniNull() {
        return isNull(getDniAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     *
     * @return true if default value
     *
     * @see #getDni
     * @see #setDni
     */
    public final boolean isDniDefaultValue() {
        return isDefaultValue(getDniAttribute(getMtDatabase()));
    }


    /* Attribute 'nombre' */
    /**
     * Attribute <code>nombre</code> cache ID
     */
    private static int nombreCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("nombre", CID));

    /**
     * Gets the <code>nombre</code> attribute descriptor. This method supports
     * advanced MATISSE programming techniques such as dynamically modifying the
     * schema.
     *
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNombreAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute) db.getCachedObject(nombreCID);
    }

    /**
     * Gets the <code>nombre</code> attribute value.
     *
     * @return the value
     *
     * @see #setNombre
     * @see #removeNombre
     */
    public final String getNombre() {
        return getString(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>nombre</code> attribute value.
     *
     * @param val the new value
     *
     * @see #getNombre
     * @see #removeNombre
     */
    public final void setNombre(String val) {
        setString(getNombreAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>nombre</code> attribute value. Falls back to
     * the default value is there is one. If the attribute has no default value,
     * it must be set to a new value before commit.
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final void removeNombre() {
        removeValue(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     *
     * @return true if null value
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final boolean isNombreNull() {
        return isNull(getNombreAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     *
     * @return true if default value
     *
     * @see #getNombre
     * @see #setNombre
     */
    public final boolean isNombreDefaultValue() {
        return isDefaultValue(getNombreAttribute(getMtDatabase()));
    }


    /* Attribute 'apellidos' */
    /**
     * Attribute <code>apellidos</code> cache ID
     */
    private static int apellidosCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("apellidos", CID));

    /**
     * Gets the <code>apellidos</code> attribute descriptor. This method
     * supports advanced MATISSE programming techniques such as dynamically
     * modifying the schema.
     *
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getApellidosAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute) db.getCachedObject(apellidosCID);
    }

    /**
     * Gets the <code>apellidos</code> attribute value.
     *
     * @return the value
     *
     * @see #setApellidos
     * @see #removeApellidos
     */
    public final String getApellidos() {
        return getString(getApellidosAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>apellidos</code> attribute value.
     *
     * @param val the new value
     *
     * @see #getApellidos
     * @see #removeApellidos
     */
    public final void setApellidos(String val) {
        setString(getApellidosAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>apellidos</code> attribute value. Falls back to
     * the default value is there is one. If the attribute has no default value,
     * it must be set to a new value before commit.
     *
     * @see #getApellidos
     * @see #setApellidos
     */
    public final void removeApellidos() {
        removeValue(getApellidosAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     *
     * @return true if null value
     *
     * @see #getApellidos
     * @see #setApellidos
     */
    public final boolean isApellidosNull() {
        return isNull(getApellidosAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     *
     * @return true if default value
     *
     * @see #getApellidos
     * @see #setApellidos
     */
    public final boolean isApellidosDefaultValue() {
        return isDefaultValue(getApellidosAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

 /* Relationship 'tieneVivienda' */
    /**
     * Relationship <code>tieneVivienda</code> cache ID
     */
    private static int tieneViviendaCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("tieneVivienda", CID));

    /**
     * Gets the <code>tieneVivienda</code> relationship descriptor. This method
     * supports advanced MATISSE programming techniques such as dynamically
     * modifying the schema.
     *
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getTieneViviendaRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship) db.getCachedObject(tieneViviendaCID);
    }

    /**
     * Gets the <code>tieneVivienda</code> relationship's successors.
     *
     * @return an array of objects
     *
     * @see #getTieneViviendaSize
     * @see #tieneViviendaIterator
     * @see #setTieneVivienda
     * @see #removeTieneVivienda
     */
    public final inmobiliaria.Vivienda[] getTieneVivienda() {
        return (inmobiliaria.Vivienda[]) getSuccessors(getTieneViviendaRelationship(getMtDatabase()), inmobiliaria.Vivienda.class);
    }

    /**
     * Counts the <code>tieneVivienda</code> relationship's successors.
     *
     * @return the number of successors
     *
     * @see #getTieneVivienda
     * @see #tieneViviendaIterator
     * @see #setTieneVivienda
     * @see #removeTieneVivienda
     */
    public final int getTieneViviendaSize() {
        return getSuccessorSize(getTieneViviendaRelationship(getMtDatabase()));
    }

    /**
     * Opens an iterator on the <code>tieneVivienda</code> relationship's
     * successors.
     *
     * @param <E> a MtObject class * @return an object iterator
     *
     * @see #getTieneVivienda
     * @see #getTieneViviendaSize
     * @see #setTieneVivienda
     * @see #removeTieneVivienda
     */
    public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> tieneViviendaIterator() {
        return this.<E>successorIterator(getTieneViviendaRelationship(getMtDatabase()), inmobiliaria.Vivienda.class);
    }

    /**
     * Sets the <code>tieneVivienda</code> relationship's successors.
     *
     * @param succs an array of objects
     *
     * @see #getTieneVivienda
     * @see #getTieneViviendaSize
     * @see #tieneViviendaIterator
     * @see #removeTieneVivienda
     */
    public final void setTieneVivienda(inmobiliaria.Vivienda[] succs) {
        setSuccessors(getTieneViviendaRelationship(getMtDatabase()), succs);
    }

    /**
     * Inserts one object at the beginning of the existing
     * <code>tieneVivienda</code> successors list.
     *
     * @param succ the object to add
     *
     * @see #getTieneVivienda
     * @see #getTieneViviendaSize
     * @see #tieneViviendaIterator
     * @see #setTieneVivienda
     * @see #removeTieneVivienda
     */
    public final void prependTieneVivienda(inmobiliaria.Vivienda succ) {
        prependSuccessor(getTieneViviendaRelationship(getMtDatabase()), succ);
    }

    /**
     * Adds one object to the end of the existing <code>tieneVivienda</code>
     * successors list.
     *
     * @param succ the object to add
     *
     * @see #getTieneVivienda
     * @see #setTieneVivienda
     * @see #removeTieneVivienda
     * @see #getTieneViviendaSize
     * @see #tieneViviendaIterator
     */
    public final void appendTieneVivienda(inmobiliaria.Vivienda succ) {
        appendSuccessor(getTieneViviendaRelationship(getMtDatabase()), succ);
    }

    /**
     * Adds multiple objects to the end of the existing
     * <code>tieneVivienda</code> successors list.
     *
     * @param succs an array of objects to add
     *
     * @see #getTieneVivienda
     * @see #setTieneVivienda
     * @see #removeTieneVivienda
     * @see #getTieneViviendaSize
     * @see #tieneViviendaIterator
     */
    public final void appendTieneVivienda(inmobiliaria.Vivienda[] succs) {
        addSuccessors(getTieneViviendaRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes objects from the <code>tieneVivienda</code> successors list.
     *
     * @param succs an array of objects to remove
     *
     * @see #getTieneVivienda
     * @see #setTieneVivienda
     * @see #getTieneViviendaSize
     * @see #tieneViviendaIterator
     */
    public void removeTieneVivienda(inmobiliaria.Vivienda[] succs) {
        removeSuccessors(getTieneViviendaRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes one object from the <code>tieneVivienda</code> successors list.
     *
     * @param succ the object to remove
     *
     * @see #getTieneVivienda
     * @see #setTieneVivienda
     * @see #getTieneViviendaSize
     * @see #tieneViviendaIterator
     */
    public void removeTieneVivienda(inmobiliaria.Vivienda succ) {
        removeSuccessor(getTieneViviendaRelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>tieneVivienda</code> successors. When the minimum
     * cardinality is 1, a new successor must be set before commit.
     */
    public final void clearTieneVivienda() {
        clearSuccessors(getTieneViviendaRelationship(getMtDatabase()));
    }


    /*
     * SQL Method access methods
     */
    /**
     * SQL Method call.
     *
     * @return the SQL Method return value
     */
    public Float calcularDescuento(Vivienda vivienda)
            throws java.sql.SQLException {
        float resultado = 0f;
        float total = 0f;
        Vivienda[] vivs = getTieneVivienda();
        switch (vivs.length) {
            case 0:
                break;
            case 1:
                total = 5;
                break;
            case 2:
                total = 8;
                break;
            case 3:
                total = 10;
                break;
            default:
                total = 10 + (vivs.length - 3);
                break;
        }
        resultado = vivienda.calcularPrecioEspecial(total);
        return resultado;
    }

    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */
    /**
     * Default constructor provided as an example. You may delete this
     * constructor or modify it to suit your needs. If you modify it, please
     * revise this comment accordingly.
     *
     * @param db a database
     */
    public Cliente(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method. You may delete this method or
     * modify it to suit your needs. If you modify it, please revise this
     * comment accordingly.
     *
     * @return a string
     */
    public java.lang.String toString() {
        return "Cliente " + getNombre() + " " + getApellidos() + " con DNI: " + getDni();
    }
}
