/*
 * Ventana.java
 *
 * Generated with Matisse Schema Definition Language 9.1.12
 * Generation date: Mon Feb 17 13:35:52 2020
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

package inmobiliaria;

import com.matisse.reflect.*;

/**
 * <code>Ventana</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Ventana extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.12
     * Generation Date: Mon Feb 17 13:35:52 2020
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Ventana</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("inmobiliaria.Ventana"));

    /**
     * Gets the <code>Ventana</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Ventana(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Ventana(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Ventana.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Ventana.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Ventana.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Ventana.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'dimensiones' */

    /** Attribute <code>dimensiones</code> cache ID */
    private static int dimensionesCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("dimensiones",CID));

    /**
     * Gets the <code>dimensiones</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getDimensionesAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(dimensionesCID);
    }


    /**
     * Gets the <code>dimensiones</code> attribute value.
     * @return the value
     *
     * @see #setDimensiones
     * @see #removeDimensiones
     */
    public final int getDimensiones() {
        return getInteger(getDimensionesAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>dimensiones</code> attribute value.
     * @param val the new value
     *
     * @see #getDimensiones
     * @see #removeDimensiones
     */
    public final void setDimensiones(int val) {
        setInteger(getDimensionesAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>dimensiones</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getDimensiones
     * @see #setDimensiones
     */
    public final void removeDimensiones() {
        removeValue(getDimensionesAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getDimensiones
     * @see #setDimensiones
     */
    public final boolean isDimensionesNull() {
        return isNull(getDimensionesAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getDimensiones
     * @see #setDimensiones
     */
    public final boolean isDimensionesDefaultValue() {
        return isDefaultValue(getDimensionesAttribute(getMtDatabase()));
    }


    /* Attribute 'orientacion' */

    /** Attribute <code>orientacion</code> cache ID */
    private static int orientacionCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("orientacion",CID));

    /**
     * Gets the <code>orientacion</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getOrientacionAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(orientacionCID);
    }


    /**
     * Gets the <code>orientacion</code> attribute value.
     * @return the value
     *
     * @see #setOrientacion
     * @see #removeOrientacion
     */
    public final String getOrientacion() {
        return getString(getOrientacionAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>orientacion</code> attribute value.
     * @param val the new value
     *
     * @see #getOrientacion
     * @see #removeOrientacion
     */
    public final void setOrientacion(String val) {
        setString(getOrientacionAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>orientacion</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getOrientacion
     * @see #setOrientacion
     */
    public final void removeOrientacion() {
        removeValue(getOrientacionAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getOrientacion
     * @see #setOrientacion
     */
    public final boolean isOrientacionNull() {
        return isNull(getOrientacionAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getOrientacion
     * @see #setOrientacion
     */
    public final boolean isOrientacionDefaultValue() {
        return isDefaultValue(getOrientacionAttribute(getMtDatabase()));
    }


    /* Attribute 'climalite' */

    /** Attribute <code>climalite</code> cache ID */
    private static int climaliteCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("climalite",CID));

    /**
     * Gets the <code>climalite</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getClimaliteAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(climaliteCID);
    }


    /**
     * Gets the <code>climalite</code> attribute value.
     * @return the value
     *
     * @see #setClimalite
     * @see #removeClimalite
     */
    public final boolean getClimalite() {
        return getBoolean(getClimaliteAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>climalite</code> attribute value.
     * @param val the new value
     *
     * @see #getClimalite
     * @see #removeClimalite
     */
    public final void setClimalite(boolean val) {
        setBoolean(getClimaliteAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>climalite</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getClimalite
     * @see #setClimalite
     */
    public final void removeClimalite() {
        removeValue(getClimaliteAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getClimalite
     * @see #setClimalite
     */
    public final boolean isClimaliteNull() {
        return isNull(getClimaliteAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getClimalite
     * @see #setClimalite
     */
    public final boolean isClimaliteDefaultValue() {
        return isDefaultValue(getClimaliteAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'perteneceA' */

    /** Relationship <code>perteneceA</code> cache ID */
    private static int perteneceACID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("perteneceA",CID));

    /**
     * Gets the <code>perteneceA</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getPerteneceARelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(perteneceACID);
    }

    /**
     * Gets the <code>perteneceA</code> relationship's successors.
     * @return an array of objects
     *
     * @see #getPerteneceASize
     * @see #perteneceAIterator
     * @see #setPerteneceA
     * @see #removePerteneceA
     */
    public final inmobiliaria.Vivienda[] getPerteneceA() {
        return (inmobiliaria.Vivienda[])getSuccessors(getPerteneceARelationship(getMtDatabase()), inmobiliaria.Vivienda.class);
    }

    /**
     * Counts the <code>perteneceA</code> relationship's successors.
     * @return the number of successors
     *
     * @see #getPerteneceA
     * @see #perteneceAIterator
     * @see #setPerteneceA
     * @see #removePerteneceA
     */
    public final int getPerteneceASize() {
        return getSuccessorSize(getPerteneceARelationship(getMtDatabase()));
    }

    /**
     * Opens an iterator on the <code>perteneceA</code> relationship's successors.
     * @param <E> a MtObject class     * @return an object iterator
     *
     * @see #getPerteneceA
     * @see #getPerteneceASize
     * @see #setPerteneceA
     * @see #removePerteneceA
     */
    public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> perteneceAIterator() {
        return this.<E>successorIterator(getPerteneceARelationship(getMtDatabase()), inmobiliaria.Vivienda.class);
    }

    /**
     * Sets the <code>perteneceA</code> relationship's successors.
     * @param succs an array of objects
     *
     * @see #getPerteneceA
     * @see #getPerteneceASize
     * @see #perteneceAIterator
     * @see #removePerteneceA
     */
    public final void setPerteneceA(inmobiliaria.Vivienda[] succs) {
        setSuccessors(getPerteneceARelationship(getMtDatabase()), succs);
    }

    /**
     * Inserts one object at the beginning of the existing <code>perteneceA</code> successors list.
     * @param succ the object to add
     *
     * @see #getPerteneceA
     * @see #getPerteneceASize
     * @see #perteneceAIterator
     * @see #setPerteneceA
     * @see #removePerteneceA
     */
    public final void prependPerteneceA(inmobiliaria.Vivienda succ) {
        prependSuccessor(getPerteneceARelationship(getMtDatabase()), succ);
    }

    /**
     * Adds one object to the end of the existing <code>perteneceA</code> successors list.
     * @param succ the object to add
     *
     * @see #getPerteneceA
     * @see #setPerteneceA
     * @see #removePerteneceA
     * @see #getPerteneceASize
     * @see #perteneceAIterator
     */
    public final void appendPerteneceA(inmobiliaria.Vivienda succ) {
        appendSuccessor(getPerteneceARelationship(getMtDatabase()), succ);
    }
    /** Adds multiple objects to the end of the existing <code>perteneceA</code> successors list.
     * @param succs an array of objects to add
     *
     * @see #getPerteneceA
     * @see #setPerteneceA
     * @see #removePerteneceA
     * @see #getPerteneceASize
     * @see #perteneceAIterator
     */
    public final void appendPerteneceA(inmobiliaria.Vivienda[] succs) {
        addSuccessors(getPerteneceARelationship(getMtDatabase()), succs);
    }

    /**
     * Removes objects from the <code>perteneceA</code> successors list.
     * @param succs an array of objects to remove
     *
     * @see #getPerteneceA
     * @see #setPerteneceA
     * @see #getPerteneceASize
     * @see #perteneceAIterator
     */
    public void removePerteneceA(inmobiliaria.Vivienda[] succs) {
        removeSuccessors(getPerteneceARelationship(getMtDatabase()), succs);
    }

    /**
     * Removes one object from the <code>perteneceA</code> successors list.
     * @param succ the object to remove
     *
     * @see #getPerteneceA
     * @see #setPerteneceA
     * @see #getPerteneceASize
     * @see #perteneceAIterator
     */
    public void removePerteneceA(inmobiliaria.Vivienda succ) {
        removeSuccessor(getPerteneceARelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>perteneceA</code> successors.  When the minimum cardinality
     * is 1, a new successor must be set before commit.
     */
    public final void clearPerteneceA() {
        clearSuccessors(getPerteneceARelationship(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Ventana(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Ventana]";
    }
}
