package POJOs;
// Generated 26-ene-2022 13:45:03 by Hibernate Tools 4.3.1



/**
 * Juanes generated by hbm2java
 */
public class Juanes  implements java.io.Serializable {


     private int n;

    public Juanes() {
    }

    public Juanes(int n) {
       this.n = n;
    }
   
    public int getN() {
        return this.n;
    }
    
    public void setN(int n) {
        this.n = n;
    }




}


