package POJOs_origen;
// Generated 31-ene-2022 10:13:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private Integer idEquipo;
     private String nombreEquipo;
     private String ciudad;
     private String web;
     private Integer puntos;
     private Set partidosesForElocal = new HashSet(0);
     private Set partidosesForEvisitante = new HashSet(0);
     private Set jugadoreses = new HashSet(0);

    public Equipos() {
    }

	
    public Equipos(String nombreEquipo, String ciudad) {
        this.nombreEquipo = nombreEquipo;
        this.ciudad = ciudad;
    }
    public Equipos(String nombreEquipo, String ciudad, String web, Integer puntos, Set partidosesForElocal, Set partidosesForEvisitante, Set jugadoreses) {
       this.nombreEquipo = nombreEquipo;
       this.ciudad = ciudad;
       this.web = web;
       this.puntos = puntos;
       this.partidosesForElocal = partidosesForElocal;
       this.partidosesForEvisitante = partidosesForEvisitante;
       this.jugadoreses = jugadoreses;
    }
   
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
    public String getNombreEquipo() {
        return this.nombreEquipo;
    }
    
    public void setNombreEquipo(String nombreEquipo) {
        this.nombreEquipo = nombreEquipo;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }
    public Integer getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(Integer puntos) {
        this.puntos = puntos;
    }
    public Set getPartidosesForElocal() {
        return this.partidosesForElocal;
    }
    
    public void setPartidosesForElocal(Set partidosesForElocal) {
        this.partidosesForElocal = partidosesForElocal;
    }
    public Set getPartidosesForEvisitante() {
        return this.partidosesForEvisitante;
    }
    
    public void setPartidosesForEvisitante(Set partidosesForEvisitante) {
        this.partidosesForEvisitante = partidosesForEvisitante;
    }
    public Set getJugadoreses() {
        return this.jugadoreses;
    }
    
    public void setJugadoreses(Set jugadoreses) {
        this.jugadoreses = jugadoreses;
    }




}


