package POJOs_origen;
// Generated 31-ene-2022 10:13:35 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Jugadores generated by hbm2java
 */
public class Jugadores  implements java.io.Serializable {


     private Integer idJugador;
     private Equipos equipos;
     private String nombre;
     private String apellido;
     private String puesto;
     private Date fechaAlta;
     private Integer salario;
     private Integer altura;

    public Jugadores() {
    }

	
    public Jugadores(String nombre, String apellido) {
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Jugadores(Equipos equipos, String nombre, String apellido, String puesto, Date fechaAlta, Integer salario, Integer altura) {
       this.equipos = equipos;
       this.nombre = nombre;
       this.apellido = apellido;
       this.puesto = puesto;
       this.fechaAlta = fechaAlta;
       this.salario = salario;
       this.altura = altura;
    }
   
    public Integer getIdJugador() {
        return this.idJugador;
    }
    
    public void setIdJugador(Integer idJugador) {
        this.idJugador = idJugador;
    }
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public Integer getSalario() {
        return this.salario;
    }
    
    public void setSalario(Integer salario) {
        this.salario = salario;
    }
    public Integer getAltura() {
        return this.altura;
    }
    
    public void setAltura(Integer altura) {
        this.altura = altura;
    }




}


