/*
 * Zona.java
 *
 * Generated with Matisse Schema Definition Language 9.1.12
 * Generation date: Thu Feb 24 08:48:06 2022
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

package inmobiliaria;

import com.matisse.reflect.*;

/**
 * <code>Zona</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Zona extends com.matisse.reflect.MtObject {
	public Float calcularMediaPorZona()
			throws java.sql.SQLException {
		float total = 0f;
		Vivienda[] vivs = getContiene();
		float suma = 0f;
		for (Vivienda v : vivs) {
			suma = suma + v.calcularPrecio();
		}
		total = suma / vivs.length;
		return total;
	}
	// BEGIN Matisse SDL Generated Code
	// DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
	/*
	 * Generated with Matisse Schema Definition Language 9.1.12
	 * Generation Date: Thu Feb 24 08:48:06 2022
	 */

	/*
	 * Class variables and methods
	 */

	/** Class <code>Zona</code> cache ID */
	private static int CID = com.matisse.MtDatabase
			.allocCID(new com.matisse.reflect.MtClass.Loader("inmobiliaria.Zona"));

	/**
	 * Gets the <code>Zona</code> class descriptor.
	 * This method supports advanced MATISSE programming techniques such as
	 * dynamically modifying the schema.
	 * 
	 * @param db a database
	 * @return a class descriptor
	 */
	public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
		return (com.matisse.reflect.MtClass) db.getCachedObject(CID);
	}

	/**
	 * Factory constructor. This constructor is called by
	 * <code>MtObjectFactory</code>.
	 * It is public for technical reasons but is not intended to be called
	 * directly by user methods.
	 * 
	 * @param db    a database
	 * @param mtOid an existing object ID in the database
	 */
	public Zona(com.matisse.MtDatabase db, int mtOid) {
		super(db, mtOid);
	}

	/**
	 * Cascaded constructor, used by subclasses to create a new object in the
	 * database.
	 * It is protected for technical reasons but is not intended to be called
	 * directly by user methods.
	 * 
	 * @param mtCls a class descriptor (the class to instantiate)
	 */
	protected Zona(com.matisse.reflect.MtClass mtCls) {
		super(mtCls);
	}

	/**
	 * Opens an iterator on all instances of this class (and its subclasses).
	 * 
	 * @param <E> a MtObject class * @param db a database
	 * @return an object iterator
	 */
	public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(
			com.matisse.MtDatabase db) {
		return getClass(db).<E>instanceIterator(Zona.class);
	}

	/**
	 * Opens an iterator on all instances of this class (and its subclasses).
	 * 
	 * @param <E>             a MtObject class * @param db a database
	 * @param numObjPerBuffer maximum number of objects to fetch from the server at
	 *                        a time
	 * @return an object iterator
	 */
	public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(
			com.matisse.MtDatabase db, int numObjPerBuffer) {
		return getClass(db).<E>instanceIterator(numObjPerBuffer, Zona.class);
	}

	/**
	 * Counts the number of instances of this class (and its subclasses).
	 * 
	 * @param db a database
	 * @return total number of instances
	 */
	public static long getInstanceNumber(com.matisse.MtDatabase db) {
		return getClass(db).getInstanceNumber();
	}

	/**
	 * Opens an iterator on all own instances of this class (excluding subclasses).
	 * 
	 * @param <E> a MtObject class * @param db a database
	 * @return an object iterator
	 */
	public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(
			com.matisse.MtDatabase db) {
		return getClass(db).<E>ownInstanceIterator(Zona.class);
	}

	/**
	 * Opens an iterator on all own instances of this class (excluding subclasses).
	 * 
	 * @param <E>             a MtObject class * @param db a database
	 * @param numObjPerBuffer maximum number of objects to fetch from the server at
	 *                        a time
	 * @return an object iterator
	 */
	public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(
			com.matisse.MtDatabase db, int numObjPerBuffer) {
		return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Zona.class);
	}

	/**
	 * Counts the number of own instances of this class (excluding subclasses).
	 * 
	 * @param db a database
	 * @return total number of instances
	 */
	public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
		return getClass(db).getOwnInstanceNumber();
	}

	/*
	 * Attribute access methods
	 */

	/* Attribute 'id' */

	/** Attribute <code>id</code> cache ID */
	private static int idCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("id", CID));

	/**
	 * Gets the <code>id</code> attribute descriptor.
	 * This method supports advanced MATISSE programming techniques such as
	 * dynamically modifying the schema.
	 * 
	 * @param db the database containing the attribute
	 * @return the attribute descriptor object
	 */
	public static com.matisse.reflect.MtAttribute getIdAttribute(com.matisse.MtDatabase db) {
		return (com.matisse.reflect.MtAttribute) db.getCachedObject(idCID);
	}

	/**
	 * Gets the <code>id</code> attribute value.
	 * 
	 * @return the value
	 *
	 * @see #setId
	 * @see #removeId
	 */
	public final int getId() {
		return getInteger(getIdAttribute(getMtDatabase()));
	}

	/**
	 * Sets the <code>id</code> attribute value.
	 * 
	 * @param val the new value
	 *
	 * @see #getId
	 * @see #removeId
	 */
	public final void setId(int val) {
		setInteger(getIdAttribute(getMtDatabase()), val);
	}

	/**
	 * Removes the current <code>id</code> attribute value.
	 * Falls back to the default value is there is one. If the attribute
	 * has no default value, it must be set to a new value before commit.
	 *
	 * @see #getId
	 * @see #setId
	 */
	public final void removeId() {
		removeValue(getIdAttribute(getMtDatabase()));
	}

	/**
	 * Check if nullable attribute value is set to MT_NULL.
	 * 
	 * @return true if null value
	 *
	 * @see #getId
	 * @see #setId
	 */
	public final boolean isIdNull() {
		return isNull(getIdAttribute(getMtDatabase()));
	}

	/**
	 * Check if attribute value is set to its default value.
	 * 
	 * @return true if default value
	 *
	 * @see #getId
	 * @see #setId
	 */
	public final boolean isIdDefaultValue() {
		return isDefaultValue(getIdAttribute(getMtDatabase()));
	}

	/* Attribute 'nombre' */

	/** Attribute <code>nombre</code> cache ID */
	private static int nombreCID = com.matisse.MtDatabase
			.allocCID(new com.matisse.reflect.MtAttribute.Loader("nombre", CID));

	/**
	 * Gets the <code>nombre</code> attribute descriptor.
	 * This method supports advanced MATISSE programming techniques such as
	 * dynamically modifying the schema.
	 * 
	 * @param db the database containing the attribute
	 * @return the attribute descriptor object
	 */
	public static com.matisse.reflect.MtAttribute getNombreAttribute(com.matisse.MtDatabase db) {
		return (com.matisse.reflect.MtAttribute) db.getCachedObject(nombreCID);
	}

	/**
	 * Gets the <code>nombre</code> attribute value.
	 * 
	 * @return the value
	 *
	 * @see #setNombre
	 * @see #removeNombre
	 */
	public final String getNombre() {
		return getString(getNombreAttribute(getMtDatabase()));
	}

	/**
	 * Sets the <code>nombre</code> attribute value.
	 * 
	 * @param val the new value
	 *
	 * @see #getNombre
	 * @see #removeNombre
	 */
	public final void setNombre(String val) {
		setString(getNombreAttribute(getMtDatabase()), val);
	}

	/**
	 * Removes the current <code>nombre</code> attribute value.
	 * Falls back to the default value is there is one. If the attribute
	 * has no default value, it must be set to a new value before commit.
	 *
	 * @see #getNombre
	 * @see #setNombre
	 */
	public final void removeNombre() {
		removeValue(getNombreAttribute(getMtDatabase()));
	}

	/**
	 * Check if nullable attribute value is set to MT_NULL.
	 * 
	 * @return true if null value
	 *
	 * @see #getNombre
	 * @see #setNombre
	 */
	public final boolean isNombreNull() {
		return isNull(getNombreAttribute(getMtDatabase()));
	}

	/**
	 * Check if attribute value is set to its default value.
	 * 
	 * @return true if default value
	 *
	 * @see #getNombre
	 * @see #setNombre
	 */
	public final boolean isNombreDefaultValue() {
		return isDefaultValue(getNombreAttribute(getMtDatabase()));
	}

	/* Attribute 'valorMetro' */

	/** Attribute <code>valorMetro</code> cache ID */
	private static int valorMetroCID = com.matisse.MtDatabase
			.allocCID(new com.matisse.reflect.MtAttribute.Loader("valorMetro", CID));

	/**
	 * Gets the <code>valorMetro</code> attribute descriptor.
	 * This method supports advanced MATISSE programming techniques such as
	 * dynamically modifying the schema.
	 * 
	 * @param db the database containing the attribute
	 * @return the attribute descriptor object
	 */
	public static com.matisse.reflect.MtAttribute getValorMetroAttribute(com.matisse.MtDatabase db) {
		return (com.matisse.reflect.MtAttribute) db.getCachedObject(valorMetroCID);
	}

	/**
	 * Gets the <code>valorMetro</code> attribute value.
	 * 
	 * @return the value
	 *
	 * @see #setValorMetro
	 * @see #removeValorMetro
	 */
	public final int getValorMetro() {
		return getInteger(getValorMetroAttribute(getMtDatabase()));
	}

	/**
	 * Sets the <code>valorMetro</code> attribute value.
	 * 
	 * @param val the new value
	 *
	 * @see #getValorMetro
	 * @see #removeValorMetro
	 */
	public final void setValorMetro(int val) {
		setInteger(getValorMetroAttribute(getMtDatabase()), val);
	}

	/**
	 * Removes the current <code>valorMetro</code> attribute value.
	 * Falls back to the default value is there is one. If the attribute
	 * has no default value, it must be set to a new value before commit.
	 *
	 * @see #getValorMetro
	 * @see #setValorMetro
	 */
	public final void removeValorMetro() {
		removeValue(getValorMetroAttribute(getMtDatabase()));
	}

	/**
	 * Check if nullable attribute value is set to MT_NULL.
	 * 
	 * @return true if null value
	 *
	 * @see #getValorMetro
	 * @see #setValorMetro
	 */
	public final boolean isValorMetroNull() {
		return isNull(getValorMetroAttribute(getMtDatabase()));
	}

	/**
	 * Check if attribute value is set to its default value.
	 * 
	 * @return true if default value
	 *
	 * @see #getValorMetro
	 * @see #setValorMetro
	 */
	public final boolean isValorMetroDefaultValue() {
		return isDefaultValue(getValorMetroAttribute(getMtDatabase()));
	}

	/* Attribute 'indiceRevalorizacion' */

	/** Attribute <code>indiceRevalorizacion</code> cache ID */
	private static int indiceRevalorizacionCID = com.matisse.MtDatabase
			.allocCID(new com.matisse.reflect.MtAttribute.Loader("indiceRevalorizacion", CID));

	/**
	 * Gets the <code>indiceRevalorizacion</code> attribute descriptor.
	 * This method supports advanced MATISSE programming techniques such as
	 * dynamically modifying the schema.
	 * 
	 * @param db the database containing the attribute
	 * @return the attribute descriptor object
	 */
	public static com.matisse.reflect.MtAttribute getIndiceRevalorizacionAttribute(com.matisse.MtDatabase db) {
		return (com.matisse.reflect.MtAttribute) db.getCachedObject(indiceRevalorizacionCID);
	}

	/**
	 * Gets the <code>indiceRevalorizacion</code> attribute value.
	 * 
	 * @return the value
	 *
	 * @see #setIndiceRevalorizacion
	 * @see #removeIndiceRevalorizacion
	 */
	public final int getIndiceRevalorizacion() {
		return getInteger(getIndiceRevalorizacionAttribute(getMtDatabase()));
	}

	/**
	 * Sets the <code>indiceRevalorizacion</code> attribute value.
	 * 
	 * @param val the new value
	 *
	 * @see #getIndiceRevalorizacion
	 * @see #removeIndiceRevalorizacion
	 */
	public final void setIndiceRevalorizacion(int val) {
		setInteger(getIndiceRevalorizacionAttribute(getMtDatabase()), val);
	}

	/**
	 * Removes the current <code>indiceRevalorizacion</code> attribute value.
	 * Falls back to the default value is there is one. If the attribute
	 * has no default value, it must be set to a new value before commit.
	 *
	 * @see #getIndiceRevalorizacion
	 * @see #setIndiceRevalorizacion
	 */
	public final void removeIndiceRevalorizacion() {
		removeValue(getIndiceRevalorizacionAttribute(getMtDatabase()));
	}

	/**
	 * Check if nullable attribute value is set to MT_NULL.
	 * 
	 * @return true if null value
	 *
	 * @see #getIndiceRevalorizacion
	 * @see #setIndiceRevalorizacion
	 */
	public final boolean isIndiceRevalorizacionNull() {
		return isNull(getIndiceRevalorizacionAttribute(getMtDatabase()));
	}

	/**
	 * Check if attribute value is set to its default value.
	 * 
	 * @return true if default value
	 *
	 * @see #getIndiceRevalorizacion
	 * @see #setIndiceRevalorizacion
	 */
	public final boolean isIndiceRevalorizacionDefaultValue() {
		return isDefaultValue(getIndiceRevalorizacionAttribute(getMtDatabase()));
	}

	/*
	 * Relationship access methods
	 */

	/* Relationship 'contiene' */

	/** Relationship <code>contiene</code> cache ID */
	private static int contieneCID = com.matisse.MtDatabase
			.allocCID(new com.matisse.reflect.MtRelationship.Loader("contiene", CID));

	/**
	 * Gets the <code>contiene</code> relationship descriptor.
	 * This method supports advanced MATISSE programming techniques such as
	 * dynamically modifying the schema.
	 * 
	 * @param db a database
	 * @return a relationship descriptor object
	 */
	public static com.matisse.reflect.MtRelationship getContieneRelationship(com.matisse.MtDatabase db) {
		return (com.matisse.reflect.MtRelationship) db.getCachedObject(contieneCID);
	}

	/**
	 * Gets the <code>contiene</code> relationship's successors.
	 * 
	 * @return an array of objects
	 *
	 * @see #getContieneSize
	 * @see #contieneIterator
	 * @see #setContiene
	 * @see #removeContiene
	 */
	public final inmobiliaria.Vivienda[] getContiene() {
		return (inmobiliaria.Vivienda[]) getSuccessors(getContieneRelationship(getMtDatabase()),
				inmobiliaria.Vivienda.class);
	}

	/**
	 * Counts the <code>contiene</code> relationship's successors.
	 * 
	 * @return the number of successors
	 *
	 * @see #getContiene
	 * @see #contieneIterator
	 * @see #setContiene
	 * @see #removeContiene
	 */
	public final int getContieneSize() {
		return getSuccessorSize(getContieneRelationship(getMtDatabase()));
	}

	/**
	 * Opens an iterator on the <code>contiene</code> relationship's successors.
	 * 
	 * @param <E> a MtObject class * @return an object iterator
	 *
	 * @see #getContiene
	 * @see #getContieneSize
	 * @see #setContiene
	 * @see #removeContiene
	 */
	public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> contieneIterator() {
		return this.<E>successorIterator(getContieneRelationship(getMtDatabase()), inmobiliaria.Vivienda.class);
	}

	/**
	 * Sets the <code>contiene</code> relationship's successors.
	 * 
	 * @param succs an array of objects
	 *
	 * @see #getContiene
	 * @see #getContieneSize
	 * @see #contieneIterator
	 * @see #removeContiene
	 */
	public final void setContiene(inmobiliaria.Vivienda[] succs) {
		setSuccessors(getContieneRelationship(getMtDatabase()), succs);
	}

	/**
	 * Inserts one object at the beginning of the existing <code>contiene</code>
	 * successors list.
	 * 
	 * @param succ the object to add
	 *
	 * @see #getContiene
	 * @see #getContieneSize
	 * @see #contieneIterator
	 * @see #setContiene
	 * @see #removeContiene
	 */
	public final void prependContiene(inmobiliaria.Vivienda succ) {
		prependSuccessor(getContieneRelationship(getMtDatabase()), succ);
	}

	/**
	 * Adds one object to the end of the existing <code>contiene</code> successors
	 * list.
	 * 
	 * @param succ the object to add
	 *
	 * @see #getContiene
	 * @see #setContiene
	 * @see #removeContiene
	 * @see #getContieneSize
	 * @see #contieneIterator
	 */
	public final void appendContiene(inmobiliaria.Vivienda succ) {
		appendSuccessor(getContieneRelationship(getMtDatabase()), succ);
	}

	/**
	 * Adds multiple objects to the end of the existing <code>contiene</code>
	 * successors list.
	 * 
	 * @param succs an array of objects to add
	 *
	 * @see #getContiene
	 * @see #setContiene
	 * @see #removeContiene
	 * @see #getContieneSize
	 * @see #contieneIterator
	 */
	public final void appendContiene(inmobiliaria.Vivienda[] succs) {
		addSuccessors(getContieneRelationship(getMtDatabase()), succs);
	}

	/**
	 * Removes objects from the <code>contiene</code> successors list.
	 * 
	 * @param succs an array of objects to remove
	 *
	 * @see #getContiene
	 * @see #setContiene
	 * @see #getContieneSize
	 * @see #contieneIterator
	 */
	public void removeContiene(inmobiliaria.Vivienda[] succs) {
		removeSuccessors(getContieneRelationship(getMtDatabase()), succs);
	}

	/**
	 * Removes one object from the <code>contiene</code> successors list.
	 * 
	 * @param succ the object to remove
	 *
	 * @see #getContiene
	 * @see #setContiene
	 * @see #getContieneSize
	 * @see #contieneIterator
	 */
	public void removeContiene(inmobiliaria.Vivienda succ) {
		removeSuccessor(getContieneRelationship(getMtDatabase()), succ);
	}

	/**
	 * Removes all <code>contiene</code> successors. When the minimum cardinality
	 * is 1, a new successor must be set before commit.
	 */
	public final void clearContiene() {
		clearSuccessors(getContieneRelationship(getMtDatabase()));
	}

	// END of Matisse SDL Generated Code

	/*
	 * You may add your own code here...
	 */

	/**
	 * Default constructor provided as an example.
	 * You may delete this constructor or modify it to suit your needs. If you
	 * modify it, please revise this comment accordingly.
	 * 
	 * @param db a database
	 */
	public Zona(com.matisse.MtDatabase db) {
		super(getClass(db));
	}

	/**
	 * Example of <code>toString</code> method.
	 * You may delete this method or modify it to suit your needs. If you
	 * modify it, please revise this comment accordingly.
	 * 
	 * @return a string
	 */
	public java.lang.String toString() {
		return super.toString() + "[Zona]";
	}
}
