package POJOs;
// Generated 27-ene-2022 9:45:12 by Hibernate Tools 4.3.1



/**
 * Descendiente generated by hbm2java
 */
public class Descendiente  implements java.io.Serializable {


     private int id;
     private Progenitor progenitor;
     private String nombre;

    public Descendiente() {
    }

	
    public Descendiente(int id) {
        this.id = id;
    }
    public Descendiente(int id, Progenitor progenitor, String nombre) {
       this.id = id;
       this.progenitor = progenitor;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Progenitor getProgenitor() {
        return this.progenitor;
    }
    
    public void setProgenitor(Progenitor progenitor) {
        this.progenitor = progenitor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


