package POJOs;
// Generated 27-ene-2022 9:45:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Progenitor generated by hbm2java
 */
public class Progenitor  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Integer edad;
     private Set descendientes = new HashSet(0);

    public Progenitor() {
    }

	
    public Progenitor(int id) {
        this.id = id;
    }
    public Progenitor(int id, String nombre, Integer edad, Set descendientes) {
       this.id = id;
       this.nombre = nombre;
       this.edad = edad;
       this.descendientes = descendientes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Set getDescendientes() {
        return this.descendientes;
    }
    
    public void setDescendientes(Set descendientes) {
        this.descendientes = descendientes;
    }




}


