/*
 * Mujer.java
 *
 * Generated with Matisse Schema Definition Language 9.1.12
 * Generation date: Thu Feb 17 11:17:20 2022
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

package PAREJAS;

import com.matisse.reflect.*;

/**
 * <code>Mujer</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Mujer extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.12
     * Generation Date: Thu Feb 17 11:17:20 2022
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Mujer</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("PAREJAS.Mujer"));

    /**
     * Gets the <code>Mujer</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Mujer(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Mujer(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Mujer.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Mujer.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Mujer.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Mujer.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'id_mujer' */

    /** Attribute <code>id_mujer</code> cache ID */
    private static int id_mujerCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("id_mujer",CID));

    /**
     * Gets the <code>id_mujer</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getId_mujerAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(id_mujerCID);
    }


    /**
     * Gets the <code>id_mujer</code> attribute value.
     * @return the value
     *
     * @see #setId_mujer
     * @see #removeId_mujer
     */
    public final int getId_mujer() {
        return getInteger(getId_mujerAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>id_mujer</code> attribute value.
     * @param val the new value
     *
     * @see #getId_mujer
     * @see #removeId_mujer
     */
    public final void setId_mujer(int val) {
        setInteger(getId_mujerAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>id_mujer</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getId_mujer
     * @see #setId_mujer
     */
    public final void removeId_mujer() {
        removeValue(getId_mujerAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getId_mujer
     * @see #setId_mujer
     */
    public final boolean isId_mujerNull() {
        return isNull(getId_mujerAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getId_mujer
     * @see #setId_mujer
     */
    public final boolean isId_mujerDefaultValue() {
        return isDefaultValue(getId_mujerAttribute(getMtDatabase()));
    }


    /* Attribute 'nombre_mujer' */

    /** Attribute <code>nombre_mujer</code> cache ID */
    private static int nombre_mujerCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("nombre_mujer",CID));

    /**
     * Gets the <code>nombre_mujer</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNombre_mujerAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(nombre_mujerCID);
    }


    /**
     * Gets the <code>nombre_mujer</code> attribute value.
     * @return the value
     *
     * @see #setNombre_mujer
     * @see #removeNombre_mujer
     */
    public final String getNombre_mujer() {
        return getString(getNombre_mujerAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>nombre_mujer</code> attribute value.
     * @param val the new value
     *
     * @see #getNombre_mujer
     * @see #removeNombre_mujer
     */
    public final void setNombre_mujer(String val) {
        setString(getNombre_mujerAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>nombre_mujer</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getNombre_mujer
     * @see #setNombre_mujer
     */
    public final void removeNombre_mujer() {
        removeValue(getNombre_mujerAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getNombre_mujer
     * @see #setNombre_mujer
     */
    public final boolean isNombre_mujerNull() {
        return isNull(getNombre_mujerAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getNombre_mujer
     * @see #setNombre_mujer
     */
    public final boolean isNombre_mujerDefaultValue() {
        return isDefaultValue(getNombre_mujerAttribute(getMtDatabase()));
    }


    /* Attribute 'edad_mujer' */

    /** Attribute <code>edad_mujer</code> cache ID */
    private static int edad_mujerCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("edad_mujer",CID));

    /**
     * Gets the <code>edad_mujer</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getEdad_mujerAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(edad_mujerCID);
    }


    /**
     * Gets the <code>edad_mujer</code> attribute value.
     * @return the value
     *
     * @see #setEdad_mujer
     * @see #removeEdad_mujer
     */
    public final int getEdad_mujer() {
        return getInteger(getEdad_mujerAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>edad_mujer</code> attribute value.
     * @param val the new value
     *
     * @see #getEdad_mujer
     * @see #removeEdad_mujer
     */
    public final void setEdad_mujer(int val) {
        setInteger(getEdad_mujerAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>edad_mujer</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getEdad_mujer
     * @see #setEdad_mujer
     */
    public final void removeEdad_mujer() {
        removeValue(getEdad_mujerAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getEdad_mujer
     * @see #setEdad_mujer
     */
    public final boolean isEdad_mujerNull() {
        return isNull(getEdad_mujerAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getEdad_mujer
     * @see #setEdad_mujer
     */
    public final boolean isEdad_mujerDefaultValue() {
        return isDefaultValue(getEdad_mujerAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'tieneMarido' */

    /** Relationship <code>tieneMarido</code> cache ID */
    private static int tieneMaridoCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("tieneMarido",CID));

    /**
     * Gets the <code>tieneMarido</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getTieneMaridoRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(tieneMaridoCID);
    }

    /**
     * Gets the <code>tieneMarido</code> sucessor object.
     * @return an object 
     *
     * @see #setTieneMarido
     * @see #clearTieneMarido
     */
    public final PAREJAS.Hombre getTieneMarido() {
        return (PAREJAS.Hombre) getSuccessor(getTieneMaridoRelationship(getMtDatabase()));
    }

    /**
     * Sets the <code>tieneMarido</code> successor object. It is not necessary to clear the
     * relationship before setting a new successor.
     * @param succ the new successor object
     *
     * @see #getTieneMarido
     * @see #clearTieneMarido
     */
    public final void setTieneMarido(PAREJAS.Hombre succ) {
        setSuccessor(getTieneMaridoRelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>tieneMarido</code> successors.  When the minimum cardinality
     * is 1, a new successor must be set before commit.
     */
    public final void clearTieneMarido() {
        clearSuccessors(getTieneMaridoRelationship(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Mujer(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Mujer]";
    }
}
