package POJOS_origen;
// Generated 31-ene-2022 11:23:42 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Equipos generated by hbm2java
 */
public class Equipos  implements java.io.Serializable {


     private Integer idEquipo;
     private String nombreEquipo;
     private String ciudad;
     private String web;
     private Integer puntos;
     private Set<Partidos> partidosesForElocal = new HashSet<Partidos>(0);
     private Set<Partidos> partidosesForEvisitante = new HashSet<Partidos>(0);
     private Set<Jugadores> jugadoreses = new HashSet<Jugadores>(0);

    public Equipos() {
    }

	
    public Equipos(String nombreEquipo, String ciudad) {
        this.nombreEquipo = nombreEquipo;
        this.ciudad = ciudad;
    }
    public Equipos(String nombreEquipo, String ciudad, String web, Integer puntos, Set<Partidos> partidosesForElocal, Set<Partidos> partidosesForEvisitante, Set<Jugadores> jugadoreses) {
       this.nombreEquipo = nombreEquipo;
       this.ciudad = ciudad;
       this.web = web;
       this.puntos = puntos;
       this.partidosesForElocal = partidosesForElocal;
       this.partidosesForEvisitante = partidosesForEvisitante;
       this.jugadoreses = jugadoreses;
    }
   
    public Integer getIdEquipo() {
        return this.idEquipo;
    }
    
    public void setIdEquipo(Integer idEquipo) {
        this.idEquipo = idEquipo;
    }
    public String getNombreEquipo() {
        return this.nombreEquipo;
    }
    
    public void setNombreEquipo(String nombreEquipo) {
        this.nombreEquipo = nombreEquipo;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }
    public Integer getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(Integer puntos) {
        this.puntos = puntos;
    }
    public Set<Partidos> getPartidosesForElocal() {
        return this.partidosesForElocal;
    }
    
    public void setPartidosesForElocal(Set<Partidos> partidosesForElocal) {
        this.partidosesForElocal = partidosesForElocal;
    }
    public Set<Partidos> getPartidosesForEvisitante() {
        return this.partidosesForEvisitante;
    }
    
    public void setPartidosesForEvisitante(Set<Partidos> partidosesForEvisitante) {
        this.partidosesForEvisitante = partidosesForEvisitante;
    }
    public Set<Jugadores> getJugadoreses() {
        return this.jugadoreses;
    }
    
    public void setJugadoreses(Set<Jugadores> jugadoreses) {
        this.jugadoreses = jugadoreses;
    }




}


