/*
 * Ventana.java
 *
 * Generated with Matisse Schema Definition Language 9.1.12
 * Generation date: Wed Feb 16 19:43:42 2022
 */

// Note: the package and extends declarations are generated by mt_sdl, do not modify them

package inmoriliaria;

import com.matisse.reflect.*;

/**
 * <code>Ventana</code> is a schema class generated by <code>mt_sdl</code>.
 * Any user-written classes will be found at the end of the file, after
 * the '// END of Matisse SDL Generated Code' comment.
 * Attribute types, default values, and relationship minimum and maximum
 * cardinality are stored in the database itself, not in this source code.
 * For more information, see <i>Getting Started with MATISSE</i>.
 */
public class Ventana extends com.matisse.reflect.MtObject {

    // BEGIN Matisse SDL Generated Code
    // DO NOT MODIFY UNTIL THE 'END of Matisse SDL Generated Code' MARK BELOW
    /*
     * Generated with Matisse Schema Definition Language 9.1.12
     * Generation Date: Wed Feb 16 19:43:42 2022
     */

    /*
     * Class variables and methods
     */

    /** Class <code>Ventana</code> cache ID */
    private static int CID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtClass.Loader("inmoriliaria.Ventana"));

    /**
     * Gets the <code>Ventana</code> class descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a class descriptor
     */
    public static com.matisse.reflect.MtClass getClass(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtClass)db.getCachedObject(CID);
    }

    /**
     * Factory constructor. This constructor is called by <code>MtObjectFactory</code>.
     * It is public for technical reasons but is not intended to be called
     * directly by user methods.
     * @param db a database
     * @param mtOid an existing object ID in the database
     */
    public Ventana(com.matisse.MtDatabase db, int mtOid)  {
        super(db, mtOid);
    }

    /**
     * Cascaded constructor, used by subclasses to create a new object in the database.
     * It is protected for technical reasons but is not intended to be called
     * directly by user methods.
     * @param mtCls a class descriptor (the class to instantiate)
     */
    protected Ventana(com.matisse.reflect.MtClass mtCls)  {
        super(mtCls);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>instanceIterator(Ventana.class);
    }

    /**
     * Opens an iterator on all instances of this class (and its subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> instanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>instanceIterator(numObjPerBuffer, Ventana.class);
    }

    /**
     * Counts the number of instances of this class (and its subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getInstanceNumber();
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db) {
        return getClass(db).<E>ownInstanceIterator(Ventana.class);
    }

    /**
     * Opens an iterator on all own instances of this class (excluding subclasses).
     * @param <E> a MtObject class     * @param db a database
     * @param numObjPerBuffer maximum number of objects to fetch from the server at a time
     * @return an object iterator
     */
    public static <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> ownInstanceIterator(com.matisse.MtDatabase db, int numObjPerBuffer) {
        return getClass(db).<E>ownInstanceIterator(numObjPerBuffer, Ventana.class);
    }

    /**
     * Counts the number of own instances of this class (excluding subclasses).
     * @param db a database
     * @return total number of instances
     */
    public static long getOwnInstanceNumber(com.matisse.MtDatabase db) {
        return getClass(db).getOwnInstanceNumber();
    }

    /*
     * Attribute access methods
     */

    /* Attribute 'idModelo' */

    /** Attribute <code>idModelo</code> cache ID */
    private static int idModeloCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("idModelo",CID));

    /**
     * Gets the <code>idModelo</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getIdModeloAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(idModeloCID);
    }


    /**
     * Gets the <code>idModelo</code> attribute value.
     * @return the value
     *
     * @see #setIdModelo
     * @see #removeIdModelo
     */
    public final int getIdModelo() {
        return getInteger(getIdModeloAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>idModelo</code> attribute value.
     * @param val the new value
     *
     * @see #getIdModelo
     * @see #removeIdModelo
     */
    public final void setIdModelo(int val) {
        setInteger(getIdModeloAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>idModelo</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getIdModelo
     * @see #setIdModelo
     */
    public final void removeIdModelo() {
        removeValue(getIdModeloAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getIdModelo
     * @see #setIdModelo
     */
    public final boolean isIdModeloNull() {
        return isNull(getIdModeloAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getIdModelo
     * @see #setIdModelo
     */
    public final boolean isIdModeloDefaultValue() {
        return isDefaultValue(getIdModeloAttribute(getMtDatabase()));
    }


    /* Attribute 'nombreModeloVentana' */

    /** Attribute <code>nombreModeloVentana</code> cache ID */
    private static int nombreModeloVentanaCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("nombreModeloVentana",CID));

    /**
     * Gets the <code>nombreModeloVentana</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getNombreModeloVentanaAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(nombreModeloVentanaCID);
    }


    /**
     * Gets the <code>nombreModeloVentana</code> attribute value.
     * @return the value
     *
     * @see #setNombreModeloVentana
     * @see #removeNombreModeloVentana
     */
    public final String getNombreModeloVentana() {
        return getString(getNombreModeloVentanaAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>nombreModeloVentana</code> attribute value.
     * @param val the new value
     *
     * @see #getNombreModeloVentana
     * @see #removeNombreModeloVentana
     */
    public final void setNombreModeloVentana(String val) {
        setString(getNombreModeloVentanaAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>nombreModeloVentana</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getNombreModeloVentana
     * @see #setNombreModeloVentana
     */
    public final void removeNombreModeloVentana() {
        removeValue(getNombreModeloVentanaAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getNombreModeloVentana
     * @see #setNombreModeloVentana
     */
    public final boolean isNombreModeloVentanaNull() {
        return isNull(getNombreModeloVentanaAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getNombreModeloVentana
     * @see #setNombreModeloVentana
     */
    public final boolean isNombreModeloVentanaDefaultValue() {
        return isDefaultValue(getNombreModeloVentanaAttribute(getMtDatabase()));
    }


    /* Attribute 'dimension' */

    /** Attribute <code>dimension</code> cache ID */
    private static int dimensionCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("dimension",CID));

    /**
     * Gets the <code>dimension</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getDimensionAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(dimensionCID);
    }


    /**
     * Gets the <code>dimension</code> attribute value.
     * @return the value
     *
     * @see #setDimension
     * @see #removeDimension
     */
    public final int getDimension() {
        return getInteger(getDimensionAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>dimension</code> attribute value.
     * @param val the new value
     *
     * @see #getDimension
     * @see #removeDimension
     */
    public final void setDimension(int val) {
        setInteger(getDimensionAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>dimension</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getDimension
     * @see #setDimension
     */
    public final void removeDimension() {
        removeValue(getDimensionAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getDimension
     * @see #setDimension
     */
    public final boolean isDimensionNull() {
        return isNull(getDimensionAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getDimension
     * @see #setDimension
     */
    public final boolean isDimensionDefaultValue() {
        return isDefaultValue(getDimensionAttribute(getMtDatabase()));
    }


    /* Attribute 'orientacion' */

    /** Attribute <code>orientacion</code> cache ID */
    private static int orientacionCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("orientacion",CID));

    /**
     * Gets the <code>orientacion</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getOrientacionAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(orientacionCID);
    }


    /**
     * Gets the <code>orientacion</code> attribute value.
     * @return the value
     *
     * @see #setOrientacion
     * @see #removeOrientacion
     */
    public final String getOrientacion() {
        return getString(getOrientacionAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>orientacion</code> attribute value.
     * @param val the new value
     *
     * @see #getOrientacion
     * @see #removeOrientacion
     */
    public final void setOrientacion(String val) {
        setString(getOrientacionAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>orientacion</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getOrientacion
     * @see #setOrientacion
     */
    public final void removeOrientacion() {
        removeValue(getOrientacionAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getOrientacion
     * @see #setOrientacion
     */
    public final boolean isOrientacionNull() {
        return isNull(getOrientacionAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getOrientacion
     * @see #setOrientacion
     */
    public final boolean isOrientacionDefaultValue() {
        return isDefaultValue(getOrientacionAttribute(getMtDatabase()));
    }


    /* Attribute 'aislamientoClimalite' */

    /** Attribute <code>aislamientoClimalite</code> cache ID */
    private static int aislamientoClimaliteCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtAttribute.Loader("aislamientoClimalite",CID));

    /**
     * Gets the <code>aislamientoClimalite</code> attribute descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db the database containing the attribute
     * @return the attribute descriptor object
     */
    public static com.matisse.reflect.MtAttribute getAislamientoClimaliteAttribute(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtAttribute)db.getCachedObject(aislamientoClimaliteCID);
    }


    /**
     * Gets the <code>aislamientoClimalite</code> attribute value.
     * @return the value
     *
     * @see #setAislamientoClimalite
     * @see #removeAislamientoClimalite
     */
    public final String getAislamientoClimalite() {
        return getString(getAislamientoClimaliteAttribute(getMtDatabase()));
    }

    /**
     * Sets the <code>aislamientoClimalite</code> attribute value.
     * @param val the new value
     *
     * @see #getAislamientoClimalite
     * @see #removeAislamientoClimalite
     */
    public final void setAislamientoClimalite(String val) {
        setString(getAislamientoClimaliteAttribute(getMtDatabase()), val);
    }

    /**
     * Removes the current <code>aislamientoClimalite</code> attribute value.
     * Falls back to the default value is there is one.  If the attribute
     * has no default value, it must be set to a new value before commit.
     *
     * @see #getAislamientoClimalite
     * @see #setAislamientoClimalite
     */
    public final void removeAislamientoClimalite() {
        removeValue(getAislamientoClimaliteAttribute(getMtDatabase()));
    }

    /**
     * Check if nullable attribute value is set to MT_NULL.
     * @return true if null value
     *
     * @see #getAislamientoClimalite
     * @see #setAislamientoClimalite
     */
    public final boolean isAislamientoClimaliteNull() {
        return isNull(getAislamientoClimaliteAttribute(getMtDatabase()));
    }

    /**
     * Check if attribute value is set to its default value.
     * @return true if default value
     *
     * @see #getAislamientoClimalite
     * @see #setAislamientoClimalite
     */
    public final boolean isAislamientoClimaliteDefaultValue() {
        return isDefaultValue(getAislamientoClimaliteAttribute(getMtDatabase()));
    }


    /*
     * Relationship access methods
     */

    /* Relationship 'colocadaEn' */

    /** Relationship <code>colocadaEn</code> cache ID */
    private static int colocadaEnCID = com.matisse.MtDatabase.allocCID(new com.matisse.reflect.MtRelationship.Loader("colocadaEn",CID));

    /**
     * Gets the <code>colocadaEn</code> relationship descriptor.
     * This method supports advanced MATISSE programming techniques such as
     * dynamically modifying the schema.
     * @param db a database
     * @return a relationship descriptor object
     */
    public static com.matisse.reflect.MtRelationship getColocadaEnRelationship(com.matisse.MtDatabase db) {
        return (com.matisse.reflect.MtRelationship)db.getCachedObject(colocadaEnCID);
    }

    /**
     * Gets the <code>colocadaEn</code> relationship's successors.
     * @return an array of objects
     *
     * @see #getColocadaEnSize
     * @see #colocadaEnIterator
     * @see #setColocadaEn
     * @see #removeColocadaEn
     */
    public final inmoriliaria.Vivienda[] getColocadaEn() {
        return (inmoriliaria.Vivienda[])getSuccessors(getColocadaEnRelationship(getMtDatabase()), inmoriliaria.Vivienda.class);
    }

    /**
     * Counts the <code>colocadaEn</code> relationship's successors.
     * @return the number of successors
     *
     * @see #getColocadaEn
     * @see #colocadaEnIterator
     * @see #setColocadaEn
     * @see #removeColocadaEn
     */
    public final int getColocadaEnSize() {
        return getSuccessorSize(getColocadaEnRelationship(getMtDatabase()));
    }

    /**
     * Opens an iterator on the <code>colocadaEn</code> relationship's successors.
     * @param <E> a MtObject class     * @return an object iterator
     *
     * @see #getColocadaEn
     * @see #getColocadaEnSize
     * @see #setColocadaEn
     * @see #removeColocadaEn
     */
    public final <E extends com.matisse.reflect.MtObject> com.matisse.MtObjectIterator<E> colocadaEnIterator() {
        return this.<E>successorIterator(getColocadaEnRelationship(getMtDatabase()), inmoriliaria.Vivienda.class);
    }

    /**
     * Sets the <code>colocadaEn</code> relationship's successors.
     * @param succs an array of objects
     *
     * @see #getColocadaEn
     * @see #getColocadaEnSize
     * @see #colocadaEnIterator
     * @see #removeColocadaEn
     */
    public final void setColocadaEn(inmoriliaria.Vivienda[] succs) {
        setSuccessors(getColocadaEnRelationship(getMtDatabase()), succs);
    }

    /**
     * Inserts one object at the beginning of the existing <code>colocadaEn</code> successors list.
     * @param succ the object to add
     *
     * @see #getColocadaEn
     * @see #getColocadaEnSize
     * @see #colocadaEnIterator
     * @see #setColocadaEn
     * @see #removeColocadaEn
     */
    public final void prependColocadaEn(inmoriliaria.Vivienda succ) {
        prependSuccessor(getColocadaEnRelationship(getMtDatabase()), succ);
    }

    /**
     * Adds one object to the end of the existing <code>colocadaEn</code> successors list.
     * @param succ the object to add
     *
     * @see #getColocadaEn
     * @see #setColocadaEn
     * @see #removeColocadaEn
     * @see #getColocadaEnSize
     * @see #colocadaEnIterator
     */
    public final void appendColocadaEn(inmoriliaria.Vivienda succ) {
        appendSuccessor(getColocadaEnRelationship(getMtDatabase()), succ);
    }
    /** Adds multiple objects to the end of the existing <code>colocadaEn</code> successors list.
     * @param succs an array of objects to add
     *
     * @see #getColocadaEn
     * @see #setColocadaEn
     * @see #removeColocadaEn
     * @see #getColocadaEnSize
     * @see #colocadaEnIterator
     */
    public final void appendColocadaEn(inmoriliaria.Vivienda[] succs) {
        addSuccessors(getColocadaEnRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes objects from the <code>colocadaEn</code> successors list.
     * @param succs an array of objects to remove
     *
     * @see #getColocadaEn
     * @see #setColocadaEn
     * @see #getColocadaEnSize
     * @see #colocadaEnIterator
     */
    public void removeColocadaEn(inmoriliaria.Vivienda[] succs) {
        removeSuccessors(getColocadaEnRelationship(getMtDatabase()), succs);
    }

    /**
     * Removes one object from the <code>colocadaEn</code> successors list.
     * @param succ the object to remove
     *
     * @see #getColocadaEn
     * @see #setColocadaEn
     * @see #getColocadaEnSize
     * @see #colocadaEnIterator
     */
    public void removeColocadaEn(inmoriliaria.Vivienda succ) {
        removeSuccessor(getColocadaEnRelationship(getMtDatabase()), succ);
    }

    /**
     * Removes all <code>colocadaEn</code> successors.  When the minimum cardinality
     * is 1, a new successor must be set before commit.
     */
    public final void clearColocadaEn() {
        clearSuccessors(getColocadaEnRelationship(getMtDatabase()));
    }


    // END of Matisse SDL Generated Code

    /*
     * You may add your own code here...
     */

    /**
     * Default constructor provided as an example.
     * You may delete this constructor or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @param db a database
     */
    public Ventana(com.matisse.MtDatabase db) {
        super(getClass(db));
    }

    /**
     * Example of <code>toString</code> method.
     * You may delete this method or modify it to suit your needs. If you
     * modify it, please revise this comment accordingly.
     * @return a string
     */
    public java.lang.String toString() {
        return super.toString() + "[Ventana]";
    }
}
