package POJOs_mujeres_hombres_hibernate;
// Generated 17-feb-2022 9:22:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hombre generated by hbm2java
 */
@Entity
@Table(name="hombre"
    ,catalog="mujeres_hombres_hibernate"
)
public class Hombre  implements java.io.Serializable {


     private int idHombre;
     private String nombreHombre;
     private Integer edadHombre;
     private Integer salario;
     private Integer numPagas;
     private Integer retencion;
     private Set<Mujer> mujers = new HashSet<Mujer>(0);

    public Hombre() {
    }

	
    public Hombre(int idHombre) {
        this.idHombre = idHombre;
    }
    public Hombre(int idHombre, String nombreHombre, Integer edadHombre, Integer salario, Integer numPagas, Integer retencion, Set<Mujer> mujers) {
       this.idHombre = idHombre;
       this.nombreHombre = nombreHombre;
       this.edadHombre = edadHombre;
       this.salario = salario;
       this.numPagas = numPagas;
       this.retencion = retencion;
       this.mujers = mujers;
    }
   
     @Id 

    
    @Column(name="id_hombre", unique=true, nullable=false)
    public int getIdHombre() {
        return this.idHombre;
    }
    
    public void setIdHombre(int idHombre) {
        this.idHombre = idHombre;
    }

    
    @Column(name="nombre_hombre")
    public String getNombreHombre() {
        return this.nombreHombre;
    }
    
    public void setNombreHombre(String nombreHombre) {
        this.nombreHombre = nombreHombre;
    }

    
    @Column(name="edad_hombre")
    public Integer getEdadHombre() {
        return this.edadHombre;
    }
    
    public void setEdadHombre(Integer edadHombre) {
        this.edadHombre = edadHombre;
    }

    
    @Column(name="salario")
    public Integer getSalario() {
        return this.salario;
    }
    
    public void setSalario(Integer salario) {
        this.salario = salario;
    }

    
    @Column(name="num_pagas")
    public Integer getNumPagas() {
        return this.numPagas;
    }
    
    public void setNumPagas(Integer numPagas) {
        this.numPagas = numPagas;
    }

    
    @Column(name="retencion")
    public Integer getRetencion() {
        return this.retencion;
    }
    
    public void setRetencion(Integer retencion) {
        this.retencion = retencion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hombre")
    public Set<Mujer> getMujers() {
        return this.mujers;
    }
    
    public void setMujers(Set<Mujer> mujers) {
        this.mujers = mujers;
    }




}


