package POJOs_basket_destino_hibernate;
// Generated 14-feb-2022 10:48:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jugadores generated by hbm2java
 */
@Entity
@Table(name="jugadores"
    ,catalog="basket_destino2"
)
public class Jugadores  implements java.io.Serializable {


     private Integer idJugador;
     private Equipos equipos;
     private String nombre;
     private String apellido;
     private String puesto;
     private Date fechaAlta;
     private Integer salario;
     private Integer altura;

    public Jugadores() {
    }

	
    public Jugadores(String nombre, String apellido) {
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Jugadores(Equipos equipos, String nombre, String apellido, String puesto, Date fechaAlta, Integer salario, Integer altura) {
       this.equipos = equipos;
       this.nombre = nombre;
       this.apellido = apellido;
       this.puesto = puesto;
       this.fechaAlta = fechaAlta;
       this.salario = salario;
       this.altura = altura;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_jugador", unique=true, nullable=false)
    public Integer getIdJugador() {
        return this.idJugador;
    }
    
    public void setIdJugador(Integer idJugador) {
        this.idJugador = idJugador;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="num_equipo")
    public Equipos getEquipos() {
        return this.equipos;
    }
    
    public void setEquipos(Equipos equipos) {
        this.equipos = equipos;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=30)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="puesto", length=30)
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_alta", length=10)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    
    @Column(name="salario")
    public Integer getSalario() {
        return this.salario;
    }
    
    public void setSalario(Integer salario) {
        this.salario = salario;
    }

    
    @Column(name="altura")
    public Integer getAltura() {
        return this.altura;
    }
    
    public void setAltura(Integer altura) {
        this.altura = altura;
    }




}


