package POJOs_basket_destino_hibernate;
// Generated 14-feb-2022 10:48:02 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartidosId generated by hbm2java
 */
@Embeddable
public class PartidosId  implements java.io.Serializable {


     private int elocal;
     private int evisitante;
     private Date fecha;

    public PartidosId() {
    }

    public PartidosId(int elocal, int evisitante, Date fecha) {
       this.elocal = elocal;
       this.evisitante = evisitante;
       this.fecha = fecha;
    }
   


    @Column(name="elocal", nullable=false)
    public int getElocal() {
        return this.elocal;
    }
    
    public void setElocal(int elocal) {
        this.elocal = elocal;
    }


    @Column(name="evisitante", nullable=false)
    public int getEvisitante() {
        return this.evisitante;
    }
    
    public void setEvisitante(int evisitante) {
        this.evisitante = evisitante;
    }


    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PartidosId) ) return false;
		 PartidosId castOther = ( PartidosId ) other; 
         
		 return (this.getElocal()==castOther.getElocal())
 && (this.getEvisitante()==castOther.getEvisitante())
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getElocal();
         result = 37 * result + this.getEvisitante();
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


